namespace DwbHub.Application.Auth;

/// <summary>
/// Renders an email template by key (e.g. "VerifyEmail") + locale ("de"/"en")
/// against a flat model. Substitution uses {{var}} placeholders — same syntax
/// as i18next on the frontend, so server- and client-rendered strings share
/// the same mental model. Returns the rendered EmailMessage; plain-text body
/// is generated by stripping HTML + collapsing whitespace.
/// </summary>
public interface IEmailTemplateRenderer
{
    EmailMessage Render(string templateKey, string locale, string toAddress, IReadOnlyDictionary<string, string> model);
}
