using System.Reflection;
using System.Text.RegularExpressions;
using DwbHub.Application.Auth;

namespace DwbHub.Infrastructure.Email;

/// <summary>
/// Renders embedded `.html` + `.subject.txt` templates via plain `{{variable}}`
/// substitution. Same placeholder syntax as the frontend's i18next interpolation,
/// so server- and client-rendered strings share the same mental model. Plain-text
/// alternative is generated by stripping HTML tags + collapsing whitespace.
/// Stateless; thread-safe; singleton-friendly.
/// </summary>
public sealed class TemplateEmailRenderer : IEmailTemplateRenderer
{
    private static readonly Regex HtmlTagRegex = new(@"<[^>]+>", RegexOptions.Compiled);
    private static readonly Regex WhitespaceRegex = new(@"\s+", RegexOptions.Compiled);

    // Key format: "<templateKey>.<locale>.html" or ".subject.txt".
    private readonly IReadOnlyDictionary<string, string> _templates;

    public TemplateEmailRenderer()
    {
        var asm = typeof(TemplateEmailRenderer).Assembly;
        const string prefix = "DwbHub.Infrastructure.Email.Templates.";
        _templates = asm.GetManifestResourceNames()
            .Where(n => n.StartsWith(prefix, StringComparison.Ordinal))
            .ToDictionary(
                n => n.Substring(prefix.Length),
                n =>
                {
                    using var stream = asm.GetManifestResourceStream(n)
                        ?? throw new InvalidOperationException($"Resource {n} not found");
                    using var reader = new StreamReader(stream);
                    return reader.ReadToEnd();
                });
    }

    public EmailMessage Render(string templateKey, string locale, string toAddress, IReadOnlyDictionary<string, string> model)
    {
        var norm = locale is "en" ? "en" : "de"; // fallback to de
        var subject = Substitute(GetTemplate($"{templateKey}.{norm}.subject.txt"), model).Trim();
        var html    = Substitute(GetTemplate($"{templateKey}.{norm}.html"),        model);
        var text    = HtmlToText(html);
        return new EmailMessage(toAddress, subject, html, text);
    }

    private string GetTemplate(string key) =>
        _templates.TryGetValue(key, out var v)
            ? v
            : throw new InvalidOperationException(
                $"Email template not found: {key}. Available: {string.Join(", ", _templates.Keys)}");

    private static string Substitute(string template, IReadOnlyDictionary<string, string> model)
    {
        foreach (var (k, v) in model)
        {
            template = template.Replace("{{" + k + "}}", v);
        }
        return template;
    }

    private static string HtmlToText(string html)
    {
        var stripped = HtmlTagRegex.Replace(html, " ");
        return WhitespaceRegex.Replace(stripped, " ").Trim();
    }
}
