<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DwbHub.Application\DwbHub.Application.csproj" />
    <ProjectReference Include="..\DwbHub.Data\DwbHub.Data.csproj" />
    <ProjectReference Include="..\DwbHub.Bot\DwbHub.Bot.csproj" />
    <ProjectReference Include="..\DwbHub.Infrastructure\DwbHub.Infrastructure.csproj" />
    <ProjectReference Include="..\DwbHub.Core\DwbHub.Core.csproj" />
  </ItemGroup>


</Project>
